# Generated by Django 4.2 on 2023-05-05 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classification",
            name="book",
        ),
        migrations.AlterField(
            model_name="author",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="e-mail"),
        ),
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="exercises.publisher",
            ),
        ),
    ]
